import "./globals.css";
import { fontPrimaryBold } from "@/lib/fonts";



export const metadata = {
  title: "Live Auction",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontPrimaryBold.className} bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
